// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIXFlBAO-9L_tCDCChHKJF75fu0IaGk70',
    appId: '1:612244537390:web:ea6f0bb65a83eed73a1fbf',
    messagingSenderId: '612244537390',
    projectId: 'gastrackfime',
    authDomain: 'gastrackfime.firebaseapp.com',
    storageBucket: 'gastrackfime.appspot.com',
    measurementId: 'G-NC5VMW46GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP2kep0gtpSlfODc9fMraZpMxfXmJM6IQ',
    appId: '1:612244537390:android:53975353db2b2a613a1fbf',
    messagingSenderId: '612244537390',
    projectId: 'gastrackfime',
    storageBucket: 'gastrackfime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGvQJ1cvb5enNIw_PP8CvDnYf6ogR1iEs',
    appId: '1:612244537390:ios:65de8adfacae52d23a1fbf',
    messagingSenderId: '612244537390',
    projectId: 'gastrackfime',
    storageBucket: 'gastrackfime.appspot.com',
    iosBundleId: 'com.example.gastrackUanl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGvQJ1cvb5enNIw_PP8CvDnYf6ogR1iEs',
    appId: '1:612244537390:ios:65de8adfacae52d23a1fbf',
    messagingSenderId: '612244537390',
    projectId: 'gastrackfime',
    storageBucket: 'gastrackfime.appspot.com',
    iosBundleId: 'com.example.gastrackUanl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIXFlBAO-9L_tCDCChHKJF75fu0IaGk70',
    appId: '1:612244537390:web:e0967e7179b6c66a3a1fbf',
    messagingSenderId: '612244537390',
    projectId: 'gastrackfime',
    authDomain: 'gastrackfime.firebaseapp.com',
    storageBucket: 'gastrackfime.appspot.com',
    measurementId: 'G-2W1051FJ72',
  );
}
